#!/bin/sh

set -e

case "$1" in
    purge)
        ;;
    remove|upgrage|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

＃if [ "$1" = "remove" ]; then
＃    if [ -x "/usr/bin/deb-systemd-helper" ]; then
＃        deb-systemd-helper mask llmbs.service >/dev/null
＃    fi
＃fi 

＃if [ "$1" = "purge" ]; then
＃    if [ -x "/usr/bin/deb-systemd-helper" ]; then
＃        export _DEB_SYSTEMD_HELPER_PURGE=1
＃        deb-systemd-helper disable llmbs.service >/dev/null
＃        deb-systemd-helper unmask llmbs.service  >/dev/null
＃    fi
＃fi

if [ "$1" = "purge" ]; then
    update-rc.d llmbs remove >/dev/null
fi

＃if [ -d /run/systemd/system ]; then
＃    systemctl --system daemon-reload >/dev/null || true
＃fi

exit 0