#!/bin/sh
### BEGIN INIT INFO
# Provides:             llmbs
# Required-Start:       $network $remote_fs $local_fs
# Required-Stop:        $network $remote_fs $local_fs 
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start/start llmbs
### END INIT INFO

# Author: Wisdom <liuzh@llvision.com>

set -e 

DAEMON=/usr/local/llmbs/bin/llmbs
NAME=llmbs
CONFIG=/usr/local/llmbs/conf/llmbs.conf
USER=llmbs
GROUP=llmbs

test -x $DAEMON || exit 0

. /lib/init/vars.sh 

. /lib/lsb/init-functions 

case "$1" in 
    start)
        echo "Starting $NAME"
        start-stop-daemon --start --background --exec $DAEMON
        echo "."
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --stop --exec $DAEMON --
        echo "."
        ;;
    *)
        echo "Usage: $DAEMON {start|stop}"
        ;;
esac

exit 0
